# Generated by Django 2.2.13 on 2021-11-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Compact'), ('BR', 'Bridge'), ('DR', 'DSLR'), ('MR', 'Mirrorless cameras')], default='uncategorized', max_length=255),
        ),
    ]
