# Generated by Django 2.2.13 on 2021-10-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211030_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Compact'), ('BR', 'Bridge'), ('DR', 'DSLR'), ('MR', 'Mirrorless cameras')], max_length=20),
        ),
    ]
