# Generated by Django 2.2.13 on 2021-11-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211104_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='uncategorized', max_length=255),
            preserve_default=False,
        ),
    ]
