# Generated by Django 2.2.13 on 2021-10-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211030_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Compact'), ('BR', 'Bridge'), ('DR', 'DSLR'), ('MR', 'Mirrorless cameras')], max_length=2),
        ),
    ]
