# Generated by Django 2.2.13 on 2021-10-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211030_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Compact'), ('BR', 'Bridge'), ('DR', 'DSLR'), ('MR', 'Mirrorless cameras')], default='uncategorized', max_length=255),
        ),
    ]
