# Generated by Django 2.2.13 on 2021-10-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211030_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Mirrorless Cameras', 'Mirrorless Cameras'), ('DSLR', 'DSLR'), ('Bridge', 'Bridge'), ('Digital Cameras', 'Digital Cameras')], default='uncategorized', max_length=255),
        ),
    ]
